export interface ErpModuleRoute {
  path: string;
  title: string;
  group: string;
  description: string;
}

/** Placeholder routes for every major ERP module — no business logic yet. */
export const ERP_MODULES: ErpModuleRoute[] = [
  { path: "/", title: "Dashboard", group: "Core", description: "Operational overview and alerts." },
  { path: "/pos", title: "POS / Sales", group: "Sales", description: "Point of sale terminal." },
  { path: "/products", title: "Products", group: "Catalog", description: "Product master management." },
  { path: "/units", title: "Units & Quantity", group: "Catalog", description: "Units and conversions." },
  { path: "/categories", title: "Categories / Brands / Companies", group: "Catalog", description: "Taxonomy masters." },
  { path: "/barcodes", title: "Barcode & QR", group: "Catalog", description: "Codes and labels." },
  { path: "/ai-camera", title: "AI Camera Recognition", group: "Catalog", description: "Camera-assisted product match." },
  { path: "/pricing", title: "Pricing", group: "Catalog", description: "Price levels and lists." },
  { path: "/discounts", title: "Discounts", group: "Sales", description: "Discount policies." },
  { path: "/customers", title: "Customers", group: "Parties", description: "Customer master." },
  { path: "/payments", title: "Payments", group: "Sales", description: "Tender and receipts." },
  { path: "/credit", title: "Credit / Udhaar", group: "Sales", description: "Customer credit and aging." },
  { path: "/installments", title: "Installments", group: "Sales", description: "Installment plans and dues." },
  { path: "/returns", title: "Sales Returns / Exchange", group: "Sales", description: "Returns and exchanges." },
  { path: "/invoices", title: "Invoice Management", group: "Sales", description: "Invoice register and reprints." },
  { path: "/sales-management", title: "Sales Management", group: "Sales", description: "Sales register, filters, KPIs, and reports." },
  { path: "/held-sales", title: "Hold / Resume Sale", group: "Sales", description: "Parked POS carts." },
  { path: "/salesman", title: "Salesman / References", group: "Sales", description: "Commissions and targets." },
  { path: "/purchases", title: "Purchases", group: "Purchasing", description: "Purchase invoices, stock-in, supplier prices." },
  { path: "/purchase-returns", title: "Purchase Returns", group: "Purchasing", description: "Purchase return lifecycle." },
  { path: "/suppliers", title: "Suppliers", group: "Purchasing", description: "Supplier master." },
  { path: "/purchase-automation", title: "Supplier Purchase Automation", group: "Purchasing", description: "Reorder suggestions." },
  { path: "/inventory", title: "Inventory", group: "Inventory", description: "Stock on hand and movements." },
  { path: "/batches-serials", title: "Batch / Serial / Warranty / Expiry", group: "Inventory", description: "Traceability." },
  { path: "/warehouses", title: "Warehouse", group: "Inventory", description: "Warehouses and bins." },
  { path: "/stock-transfers", title: "Stock Transfer", group: "Inventory", description: "Inter-warehouse transfers." },
  { path: "/deliveries", title: "Delivery", group: "Sales", description: "Delivery notes." },
  { path: "/quotations", title: "Quotations", group: "Sales", description: "Quotes and conversion." },
  { path: "/service", title: "Service & Repair", group: "Service", description: "Job cards and repairs." },
  { path: "/warranty", title: "Warranty", group: "Service", description: "Warranty claims." },
  { path: "/accounts", title: "Accounts & Finance", group: "Finance", description: "COA and journals." },
  { path: "/banking", title: "Banking", group: "Finance", description: "Bank books and reconcile." },
  { path: "/expenses", title: "Expenses", group: "Finance", description: "Expense entry." },
  { path: "/ai-insights", title: "AI Smart Business", group: "Insights", description: "AI insights." },
  { path: "/bi", title: "Business Intelligence", group: "Insights", description: "KPI dashboards." },
  { path: "/reports", title: "Complete Reporting", group: "Insights", description: "Operational reports." },
  { path: "/crm", title: "CRM & Marketing", group: "Growth", description: "Segments and campaigns." },
  { path: "/loyalty", title: "Loyalty", group: "Growth", description: "Points and rewards." },
  { path: "/b2b", title: "B2B Wholesale Portal", group: "Channels", description: "Wholesale portal admin." },
  { path: "/online-store", title: "Online Store", group: "Channels", description: "Storefront configuration." },
  { path: "/mobile", title: "Mobile Apps", group: "Channels", description: "Mobile channel settings." },
  { path: "/documents", title: "Document Management", group: "Governance", description: "Attachments and files." },
  { path: "/approvals", title: "Approval Workflow", group: "Governance", description: "Approval inbox." },
  { path: "/users", title: "Users & Roles", group: "Admin", description: "User administration." },
  { path: "/permissions", title: "Permissions", group: "Admin", description: "Permission matrix." },
  { path: "/audit", title: "Audit Trail", group: "Governance", description: "Immutable audit log." },
  { path: "/notifications", title: "Notifications", group: "Governance", description: "Notification center." },
  { path: "/branches", title: "Multi-Branch", group: "Admin", description: "Branch administration." },
  { path: "/tax", title: "Pakistan Tax / FBR", group: "Compliance", description: "Tax readiness." },
  { path: "/import-export", title: "Import / Export", group: "Platform", description: "Data import and export." },
  { path: "/printing", title: "Printing", group: "Platform", description: "Print templates." },
  { path: "/backup", title: "Backup / DR", group: "Platform", description: "Backup and recovery." },
  { path: "/integrations", title: "API Integration", group: "Platform", description: "API keys and webhooks." },
  { path: "/settings", title: "Advanced Settings", group: "Admin", description: "Organization settings." },
  { path: "/security", title: "Security", group: "Admin", description: "Security controls." },
  { path: "/devices", title: "Device Support", group: "Platform", description: "Registered devices." },
  { path: "/transaction-linking", title: "Automatic Transaction Linking", group: "Platform", description: "Linked document trace." },
  { path: "/hr", title: "HR & Employees", group: "HR", description: "Employees, attendance, payroll." },
];
