/** Enterprise system roles — Phase 9. */
export const SYSTEM_ROLES = [
  { code: "super_admin", name: "Super Admin", description: "Platform-level full access" },
  { code: "owner", name: "Owner", description: "Organization owner with group dashboard" },
  { code: "admin", name: "Admin", description: "Organization administrator" },
  { code: "manager", name: "Manager", description: "Branch / operations manager" },
  { code: "cashier", name: "Cashier", description: "POS cashier" },
  { code: "salesman", name: "Salesman", description: "Sales representative" },
  { code: "storekeeper", name: "Storekeeper", description: "Stock receiving and store ops" },
  { code: "warehouse_manager", name: "Warehouse Manager", description: "Warehouse and transfers" },
  { code: "accountant", name: "Accountant", description: "Accounts, banking, expenses" },
  { code: "delivery_boy", name: "Delivery Boy", description: "Delivery operations" },
  { code: "technician", name: "Technician", description: "Service and warranty" },
  { code: "marketing_manager", name: "Marketing Manager", description: "Marketing and CRM view" },
] as const;

export type SystemRoleCode = (typeof SYSTEM_ROLES)[number]["code"];

export const MODULE_ACTIONS = [
  "view",
  "add",
  "edit",
  "delete",
  "approve",
  "reject",
  "print",
  "export",
  "import",
  "cancel",
  "refund",
] as const;

export type ModuleAction = (typeof MODULE_ACTIONS)[number];

export const RBAC_MODULES = [
  "products",
  "inventory",
  "customers",
  "suppliers",
  "pos",
  "purchases",
  "expenses",
  "accounts",
  "banking",
  "deliveries",
  "quotations",
  "orders",
  "service",
  "warranty",
  "reports",
  "users",
  "roles",
  "branches",
  "approvals",
  "audit",
  "payments",
  "credit",
  "transfers",
  "warehouses",
  "installments",
  "crm",
  "loyalty",
  "b2b",
  "store",
  "ai",
  "hr",
  "tax",
  "documents",
  "notifications",
  "security",
  "backup",
  "integrations",
] as const;

export type RbacModule = (typeof RBAC_MODULES)[number];

export function modulePermission(module: string, action: ModuleAction | string): string {
  return `${module}.${action}`;
}

function allModuleActions(module: string, actions: readonly ModuleAction[] = MODULE_ACTIONS): string[] {
  return actions.map((a) => modulePermission(module, a));
}

const FULL_ACCESS_MODULES = RBAC_MODULES;

/** Legacy + new keys kept for route compatibility. */
const LEGACY_ALL = [
  "dashboard.view",
  "dashboard.group_view",
  "settings.manage",
  "users.manage",
  "roles.manage",
  "permissions.manage",
  "branches.manage",
  "branches.view_all",
  "devices.manage",
  "audit.view",
  "audit.export",
  "sync.manage",
  "sync.resolve",
  "security.manage",
  "products.read",
  "products.write",
  "products.delete",
  "products.import",
  "products.export",
  "products.manage_media",
  "catalog_taxonomy.manage",
  "units.manage",
  "pricing.read",
  "pricing.write",
  "barcodes.manage",
  "barcodes.print",
  "inventory.view",
  "inventory.adjust",
  "inventory.approve_adjust",
  "inventory.count",
  "inventory.approve_count",
  "inventory.reserve",
  "inventory.serial",
  "inventory.batch",
  "inventory.transfer",
  "warehouses.manage",
  "customers.read",
  "customers.write",
  "suppliers.read",
  "suppliers.write",
  "payments.receive",
  "payments.pay",
  "payments.configure",
  "credit.manage",
  "credit.approve",
  "installments.manage",
  "ledgers.view",
  "pos.sell",
  "pos.hold",
  "pos.return",
  "pos.discount_cashier",
  "pos.discount_supervisor",
  "pos.discount_manager",
  "pos.discount_owner",
  "pos.discount_special",
  "pos.view_invoices",
  "pos.configure",
  "pos.shift",
  "purchases.read",
  "purchases.write",
  "purchases.return",
  "purchases.prices",
  "transfers.approve",
  "transfers.dispatch",
  "transfers.receive",
  "deliveries.manage",
  "quotations.read",
  "quotations.write",
  "orders.read",
  "orders.write",
  "service.manage",
  "warranty.manage",
  "accounts.read",
  "accounts.write",
  "banking.manage",
  "expenses.manage",
  "reports.finance",
  "reports.view",
  "reports.export",
  "reports.sales",
  "reports.purchases",
  "reports.stock",
  "reports.profit",
  "dashboard.view_finance",
  "dashboard.view_all_branches",
  "bi.view",
  "bi.view_all_branches",
  "crm.manage",
  "crm.view",
  "loyalty.manage",
  "loyalty.redeem",
  "loyalty.view",
  "b2b.manage",
  "b2b.order",
  "b2b.approve",
  "store.manage",
  "store.order",
  "ai.recognize",
  "ai.insights",
  "ai.manage",
  "hr.manage",
  "hr.view",
  "hr.payroll",
  "tax.manage",
  "tax.view",
  "tax.export",
  "documents.manage",
  "documents.view",
  "notifications.view",
  "notifications.broadcast",
  "notifications.manage",
  "security.view",
  "backup.manage",
  "backup.view",
  "backup.restore",
  "integrations.manage",
  "integrations.view",
  "import.execute",
  "export.execute",
  "approvals.act",
  "approvals.manage",
];

function allStandardModulePerms(): string[] {
  return FULL_ACCESS_MODULES.flatMap((m) => allModuleActions(m));
}

export function defaultPermissionsForRole(role: SystemRoleCode): string[] {
  switch (role) {
    case "super_admin":
    case "owner":
      return unique([...LEGACY_ALL, ...allStandardModulePerms()]);
    case "admin":
      return unique([
        ...LEGACY_ALL.filter((k) => k !== "security.manage" && k !== "sync.resolve"),
        ...allStandardModulePerms(),
        "approvals.act",
        "approvals.manage",
        "dashboard.view",
      ]);
    case "manager":
      return unique([
        "dashboard.view",
        "products.read",
        "products.write",
        "products.view",
        "products.add",
        "products.edit",
        "products.print",
        "products.export",
        "inventory.view",
        "inventory.adjust",
        "inventory.approve_adjust",
        "inventory.count",
        "inventory.approve_count",
        "inventory.transfer",
        ...allModuleActions("inventory", ["view", "add", "edit", "approve", "reject", "export"]),
        "customers.read",
        "customers.write",
        ...allModuleActions("customers", ["view", "add", "edit", "approve", "export"]),
        "suppliers.read",
        "suppliers.write",
        "pos.sell",
        "pos.hold",
        "pos.return",
        "pos.discount_manager",
        "pos.discount_supervisor",
        "pos.view_invoices",
        "pos.shift",
        ...allModuleActions("pos", ["view", "add", "edit", "approve", "reject", "cancel", "refund", "print"]),
        "purchases.read",
        "purchases.write",
        "purchases.return",
        ...allModuleActions("purchases", ["view", "add", "edit", "approve", "reject", "cancel", "export"]),
        "transfers.approve",
        "transfers.dispatch",
        "transfers.receive",
        "deliveries.manage",
        "quotations.read",
        "quotations.write",
        "orders.read",
        "orders.write",
        "credit.manage",
        "credit.approve",
        "payments.receive",
        "payments.pay",
        "expenses.manage",
        ...allModuleActions("expenses", ["view", "add", "edit", "approve", "reject"]),
        "reports.finance",
        "reports.view",
        "reports.sales",
        "reports.purchases",
        "reports.stock",
        "reports.profit",
        "reports.export",
        "bi.view",
        "ai.insights",
        "ai.recognize",
        "hr.view",
        "hr.manage",
        "hr.payroll",
        "tax.view",
        "tax.manage",
        "tax.export",
        "documents.view",
        "documents.manage",
        "notifications.view",
        "notifications.broadcast",
        "notifications.manage",
        "security.view",
        "security.manage",
        "backup.view",
        "backup.manage",
        "backup.restore",
        "integrations.view",
        "integrations.manage",
        "import.execute",
        "export.execute",
        "dashboard.view_finance",
        "ledgers.view",
        "approvals.act",
        "branches.view",
        ...allModuleActions("approvals", ["view", "approve", "reject"]),
        ...allModuleActions("reports", ["view", "export", "print"]),
      ]);
    case "cashier":
      return unique([
        "dashboard.view",
        "products.read",
        "products.view",
        "pos.sell",
        "pos.hold",
        "pos.return",
        "pos.discount_cashier",
        "pos.view_invoices",
        "pos.shift",
        ...allModuleActions("pos", ["view", "add", "print", "cancel"]),
        "ai.recognize",
        "customers.read",
        "customers.view",
        "payments.receive",
        "payments.view",
        "payments.add",
        "inventory.view",
        "approvals.act",
      ]);
    case "salesman":
      return unique([
        "dashboard.view",
        "products.read",
        "products.view",
        "customers.read",
        "customers.write",
        ...allModuleActions("customers", ["view", "add", "edit"]),
        "quotations.read",
        "quotations.write",
        ...allModuleActions("quotations", ["view", "add", "edit", "print"]),
        "orders.read",
        "orders.write",
        "pos.sell",
        "pos.view_invoices",
        "credit.manage",
        "credit.view",
        "credit.add",
        "approvals.act",
        "payments.receive",
      ]);
    case "storekeeper":
      return unique([
        "dashboard.view",
        "products.read",
        "products.view",
        "inventory.view",
        "inventory.adjust",
        "inventory.count",
        "inventory.serial",
        "inventory.batch",
        ...allModuleActions("inventory", ["view", "add", "edit", "import", "export"]),
        "purchases.read",
        "purchases.write",
        ...allModuleActions("purchases", ["view", "add", "edit"]),
        "warehouses.manage",
        "warehouses.view",
        "suppliers.read",
        "suppliers.view",
        "approvals.act",
      ]);
    case "warehouse_manager":
      return unique([
        "dashboard.view",
        "inventory.view",
        "inventory.adjust",
        "inventory.approve_adjust",
        "inventory.count",
        "inventory.approve_count",
        "inventory.transfer",
        "inventory.serial",
        "inventory.batch",
        ...allModuleActions("inventory", MODULE_ACTIONS),
        "warehouses.manage",
        ...allModuleActions("warehouses", ["view", "add", "edit", "delete", "approve"]),
        "transfers.approve",
        "transfers.dispatch",
        "transfers.receive",
        ...allModuleActions("transfers", ["view", "add", "edit", "approve", "reject", "cancel"]),
        "purchases.read",
        "purchases.view",
        "approvals.act",
      ]);
    case "accountant":
      return unique([
        "dashboard.view",
        "dashboard.view_finance",
        "accounts.read",
        "accounts.write",
        ...allModuleActions("accounts", MODULE_ACTIONS),
        "banking.manage",
        ...allModuleActions("banking", MODULE_ACTIONS),
        "expenses.manage",
        ...allModuleActions("expenses", MODULE_ACTIONS),
        "reports.finance",
        "reports.view",
        "reports.sales",
        "reports.purchases",
        "reports.stock",
        "reports.profit",
        "reports.export",
        "bi.view",
        "tax.view",
        "tax.manage",
        "tax.export",
        "notifications.view",
        ...allModuleActions("reports", ["view", "export", "print"]),
        "ledgers.view",
        "payments.receive",
        "payments.pay",
        "payments.configure",
        ...allModuleActions("payments", ["view", "add", "edit", "approve", "export", "print"]),
        "credit.manage",
        "customers.read",
        "suppliers.read",
        "approvals.act",
        "audit.view",
      ]);
    case "delivery_boy":
      return unique([
        "dashboard.view",
        "deliveries.manage",
        ...allModuleActions("deliveries", ["view", "edit"]),
        "customers.read",
        "customers.view",
        "pos.view_invoices",
      ]);
    case "technician":
      return unique([
        "dashboard.view",
        "service.manage",
        ...allModuleActions("service", ["view", "add", "edit", "approve", "cancel"]),
        "warranty.manage",
        ...allModuleActions("warranty", ["view", "add", "edit", "approve"]),
        "inventory.view",
        "products.read",
        "products.view",
      ]);
    case "marketing_manager":
      return unique([
        "dashboard.view",
        "customers.read",
        "customers.write",
        ...allModuleActions("customers", ["view", "add", "edit", "export"]),
        "crm.manage",
        "crm.view",
        ...allModuleActions("crm", ["view", "add", "edit", "export"]),
        "loyalty.view",
        "loyalty.manage",
        "store.manage",
        "quotations.read",
        "quotations.view",
        "reports.finance",
        "reports.view",
        "reports.export",
        "products.read",
        "products.view",
        "ai.insights",
      ]);
    default:
      return [];
  }
}

function unique(keys: string[]): string[] {
  return [...new Set(keys)].sort();
}

/** Alias map so new CRUD keys satisfy legacy route checks. */
export const PERMISSION_ALIASES: Record<string, string[]> = {
  "products.read": ["products.view"],
  "products.write": ["products.add", "products.edit"],
  "products.delete": ["products.delete"],
  "customers.read": ["customers.view"],
  "customers.write": ["customers.add", "customers.edit"],
  "purchases.read": ["purchases.view"],
  "purchases.write": ["purchases.add", "purchases.edit"],
  "accounts.read": ["accounts.view"],
  "accounts.write": ["accounts.add", "accounts.edit"],
  "expenses.manage": ["expenses.view", "expenses.add", "expenses.edit", "expenses.approve"],
  "banking.manage": ["banking.view", "banking.add", "banking.edit"],
  "inventory.view": ["inventory.view"],
};

export function permissionSatisfied(granted: string[], required: string): boolean {
  if (granted.includes(required)) return true;
  if (granted.includes("*")) return true;
  // Legacy key required, user has new CRUD key
  const aliases = PERMISSION_ALIASES[required];
  if (aliases?.some((a) => granted.includes(a))) return true;
  // New key required, user has legacy manage/write/read
  for (const [legacy, news] of Object.entries(PERMISSION_ALIASES)) {
    if (news.includes(required) && granted.includes(legacy)) return true;
  }
  return false;
}
