import { z } from "zod";
import { PermissionKeySchema, UuidSchema } from "./common.js";

/** Foundation permission catalog — modules plug in additional keys later. */
export const FOUNDATION_PERMISSIONS = [
  "dashboard.view",
  "settings.manage",
  "users.manage",
  "roles.manage",
  "permissions.manage",
  "branches.manage",
  "branches.view_all",
  "devices.manage",
  "audit.view",
  "sync.manage",
  "sync.resolve",
  "security.manage",
  "products.read",
  "products.write",
  "products.delete",
  "products.import",
  "products.export",
  "products.manage_media",
  "catalog_taxonomy.manage",
  "units.manage",
  "pricing.read",
  "pricing.write",
  "barcodes.manage",
  "barcodes.print",
  "inventory.view",
  "inventory.adjust",
  "inventory.approve_adjust",
  "inventory.count",
  "inventory.approve_count",
  "inventory.reserve",
  "inventory.serial",
  "inventory.batch",
  "inventory.transfer",
  "warehouses.manage",
  "customers.read",
  "customers.write",
  "suppliers.read",
  "suppliers.write",
  "payments.receive",
  "payments.pay",
  "payments.configure",
  "credit.manage",
  "credit.approve",
  "installments.manage",
  "ledgers.view",
  "pos.sell",
  "pos.hold",
  "pos.return",
  "pos.discount_cashier",
  "pos.discount_manager",
  "pos.discount_owner",
  "pos.view_invoices",
  "pos.configure",
  "pos.shift",
  "purchases.read",
  "purchases.write",
  "purchases.return",
  "purchases.prices",
  "transfers.approve",
  "transfers.dispatch",
  "transfers.receive",
  "deliveries.manage",
  "quotations.read",
  "quotations.write",
  "orders.read",
  "orders.write",
  "service.manage",
  "warranty.manage",
  "accounts.read",
  "accounts.write",
  "banking.manage",
  "expenses.manage",
  "reports.finance",
  "reports.view",
  "reports.export",
  "reports.sales",
  "reports.purchases",
  "reports.stock",
  "reports.profit",
  "dashboard.view_finance",
  "dashboard.view_all_branches",
  "bi.view",
  "bi.view_all_branches",
  "crm.manage",
  "crm.view",
  "loyalty.manage",
  "loyalty.redeem",
  "loyalty.view",
  "b2b.manage",
  "b2b.order",
  "b2b.approve",
  "store.manage",
  "store.order",
  "approvals.act",
  "approvals.manage",
  "dashboard.group_view",
  "audit.export",
  "sync.push",
  "sync.pull",
  "devices.register",
  "printing.manage",
  "printing.print",
  "cash_drawer.open",
  "hardware.manage",
  "ai.recognize",
  "ai.insights",
  "ai.manage",
  "hr.manage",
  "hr.view",
  "hr.payroll",
  "tax.manage",
  "tax.view",
  "tax.export",
  "documents.manage",
  "documents.view",
  "notifications.view",
  "notifications.broadcast",
  "notifications.manage",
  "security.view",
  "backup.manage",
  "backup.view",
  "backup.restore",
  "integrations.manage",
  "integrations.view",
  "import.execute",
  "export.execute",
] as const;

export type FoundationPermission = (typeof FOUNDATION_PERMISSIONS)[number];

export const AuthorizationContextSchema = z.object({
  userId: UuidSchema,
  organizationId: UuidSchema,
  branchId: UuidSchema.nullable(),
  permissions: z.array(PermissionKeySchema),
  branchIds: z.array(UuidSchema),
});

export type AuthorizationContext = z.infer<typeof AuthorizationContextSchema>;

export function hasPermission(
  ctx: AuthorizationContext,
  permission: string,
): boolean {
  return ctx.permissions.includes(permission);
}

export function requirePermission(
  ctx: AuthorizationContext,
  permission: string,
): void {
  if (!hasPermission(ctx, permission)) {
    throw new Error(`Forbidden: missing permission ${permission}`);
  }
}

export function canAccessBranch(
  ctx: AuthorizationContext,
  branchId: string,
): boolean {
  if (hasPermission(ctx, "branches.view_all")) return true;
  return ctx.branchIds.includes(branchId);
}
