/**
 * 39 product modules → grouped API routers.
 *
 * The ERP UI has 39 modules. The API stays grouped (catalog, parties, pos, …).
 * Do not split this table into 39 Express routers. Do not rename URLs.
 *
 * Delivery stays on purchasesRouter. Parties/after-sales/accounting/admin stay shared.
 */
export type ModuleApiOwnership = {
  id: string;
  module: string;
  apiGroup: string;
  mount: string;
  repository: string;
  domain: string;
};

export const MODULE_API_OWNERSHIP: readonly ModuleApiOwnership[] = [
  {
    id: "01",
    module: "Dashboard",
    apiGroup: "reports, admin",
    mount: "/api/v1/reports, /api/v1/admin/dashboard",
    repository: "ReportingRepository, AdminRepository",
    domain: "reporting.ts",
  },
  {
    id: "02",
    module: "Product Management",
    apiGroup: "catalog",
    mount: "/api/v1/catalog",
    repository: "CatalogRepository",
    domain: "pricing.ts, unit-conversion.ts",
  },
  {
    id: "03",
    module: "Barcode & QR",
    apiGroup: "catalog",
    mount: "/api/v1/catalog/barcodes, /api/v1/catalog/qr",
    repository: "CatalogRepository",
    domain: "barcode.ts",
  },
  {
    id: "04",
    module: "AI Camera Product Recognition",
    apiGroup: "ai",
    mount: "/api/v1/ai/recognize-product",
    repository: "AiRepository",
    domain: "packages/ai (no domain engine)",
  },
  {
    id: "05",
    module: "POS / Sales",
    apiGroup: "pos, parties",
    mount: "/api/v1/pos, /api/v1/parties/payments",
    repository: "PosRepository, PartiesRepository",
    domain: "sale-transaction.ts, pos-hold.ts, pos-return.ts, pos-payment.ts, pos-cart.ts, split-payment.ts",
  },
  {
    id: "06",
    module: "Quotations",
    apiGroup: "after-sales",
    mount: "/api/v1/after-sales/quotations",
    repository: "AfterSalesRepository",
    domain: "quotation-lifecycle.ts",
  },
  {
    id: "07",
    module: "Orders",
    apiGroup: "after-sales, commerce",
    mount: "/api/v1/after-sales/orders, /api/v1/b2b",
    repository: "AfterSalesRepository, CommerceRepository",
    domain: "quotation-lifecycle.ts, commerce.ts",
  },
  {
    id: "08",
    module: "Delivery",
    apiGroup: "purchases",
    mount: "/api/v1/purchases/deliveries",
    repository: "PurchasesRepository",
    domain: "delivery-lifecycle.ts, delivery-tracking.ts",
  },
  {
    id: "09",
    module: "Purchases",
    apiGroup: "purchases",
    mount: "/api/v1/purchases/invoices, /api/v1/purchases/returns",
    repository: "PurchasesRepository",
    domain: "purchase-transaction.ts, supplier-pricing.ts",
  },
  {
    id: "10",
    module: "Inventory",
    apiGroup: "inventory",
    mount: "/api/v1/inventory",
    repository: "InventoryRepository",
    domain: "stock-balances.ts, stock-ledger.ts, inventory-valuation.ts",
  },
  {
    id: "11",
    module: "Warehouses",
    apiGroup: "inventory, purchases",
    mount: "/api/v1/inventory/warehouses, /api/v1/purchases/locations, /api/v1/purchases/transfers",
    repository: "InventoryRepository, PurchasesRepository",
    domain: "transfer-lifecycle.ts",
  },
  {
    id: "12",
    module: "Customers",
    apiGroup: "parties",
    mount: "/api/v1/parties/customers, /api/v1/parties/credit",
    repository: "PartiesRepository",
    domain: "party-ledger.ts, credit.ts",
  },
  {
    id: "13",
    module: "Suppliers",
    apiGroup: "parties, purchases",
    mount: "/api/v1/parties/suppliers, /api/v1/purchases/supplier-prices",
    repository: "PartiesRepository, PurchasesRepository",
    domain: "party-ledger.ts, supplier-pricing.ts",
  },
  {
    id: "14",
    module: "Service & Repair",
    apiGroup: "after-sales",
    mount: "/api/v1/after-sales/service-jobs",
    repository: "AfterSalesRepository",
    domain: "service-lifecycle.ts",
  },
  {
    id: "15",
    module: "Warranty",
    apiGroup: "after-sales",
    mount: "/api/v1/after-sales/warranties, /api/v1/after-sales/warranty-claims",
    repository: "AfterSalesRepository",
    domain: "warranty-service.ts",
  },
  {
    id: "16",
    module: "Accounts",
    apiGroup: "accounting",
    mount: "/api/v1/accounting/accounts, /journals, /vouchers, /reports",
    repository: "AccountingRepository",
    domain: "accounting-posting.ts, finance-reports.ts",
  },
  {
    id: "17",
    module: "Banking",
    apiGroup: "accounting",
    mount: "/api/v1/accounting/bank-accounts, /bank-statements, /reconciliations",
    repository: "AccountingRepository",
    domain: "accounting-posting.ts",
  },
  {
    id: "18",
    module: "CRM & Marketing",
    apiGroup: "commerce",
    mount: "/api/v1/crm",
    repository: "CommerceRepository",
    domain: "commerce.ts",
  },
  {
    id: "19",
    module: "Reports & Analytics",
    apiGroup: "reports, ai, accounting",
    mount: "/api/v1/reports, /api/v1/ai/insights, /api/v1/accounting/reports",
    repository: "ReportingRepository, AiRepository, AccountingRepository",
    domain: "reporting.ts, finance-reports.ts",
  },
  {
    id: "20",
    module: "Salesman / Field Sales",
    apiGroup: "enterprise",
    mount: "/api/v1/hr, /api/v1/references, /api/v1/commissions",
    repository: "EnterpriseRepository",
    domain: "pos-commission.ts, enterprise.ts",
  },
  {
    id: "21",
    module: "Expenses",
    apiGroup: "accounting",
    mount: "/api/v1/accounting/expenses",
    repository: "AccountingRepository",
    domain: "accounting-posting.ts",
  },
  {
    id: "22",
    module: "Installments",
    apiGroup: "parties",
    mount: "/api/v1/parties/installments",
    repository: "PartiesRepository",
    domain: "installments.ts",
  },
  {
    id: "23",
    module: "Loyalty",
    apiGroup: "commerce",
    mount: "/api/v1/loyalty",
    repository: "CommerceRepository",
    domain: "commerce.ts",
  },
  {
    id: "24",
    module: "Documents",
    apiGroup: "enterprise",
    mount: "/api/v1/documents",
    repository: "EnterpriseRepository",
    domain: "enterprise.ts",
  },
  {
    id: "25",
    module: "Approval Workflow",
    apiGroup: "admin",
    mount: "/api/v1/admin/approvals",
    repository: "AdminRepository",
    domain: "approval-workflow.ts",
  },
  {
    id: "26",
    module: "Users & Role Management",
    apiGroup: "admin",
    mount: "/api/v1/admin/users, /api/v1/admin/roles",
    repository: "AdminRepository, UserRepository",
    domain: "rbac-catalog.ts, authz-service.ts",
  },
  {
    id: "27",
    module: "Permissions",
    apiGroup: "admin",
    mount: "/api/v1/admin/permissions, /api/v1/admin/users/:id/permissions",
    repository: "AdminRepository",
    domain: "authz-service.ts",
  },
  {
    id: "28",
    module: "Audit Trail",
    apiGroup: "admin",
    mount: "/api/v1/admin/audit",
    repository: "AdminRepository",
    domain: "audit-trail.ts",
  },
  {
    id: "29",
    module: "Notification Center",
    apiGroup: "enterprise",
    mount: "/api/v1/notifications",
    repository: "EnterpriseRepository",
    domain: "enterprise.ts",
  },
  {
    id: "30",
    module: "Multi-Branch",
    apiGroup: "admin",
    mount: "/api/v1/admin/branches",
    repository: "AdminRepository",
    domain: "DB only (no branch domain engine)",
  },
  {
    id: "31",
    module: "Tax & Pakistan Compliance",
    apiGroup: "enterprise",
    mount: "/api/v1/tax",
    repository: "EnterpriseRepository",
    domain: "pos-tax.ts, enterprise.ts",
  },
  {
    id: "32",
    module: "Import / Export",
    apiGroup: "infrastructure, catalog",
    mount: "/api/v1/data/import, /api/v1/data/export, /api/v1/catalog/import",
    repository: "InfrastructureRepository, CatalogRepository",
    domain: "apps/api import-service.ts",
  },
  {
    id: "33",
    module: "Printing",
    apiGroup: "hardware",
    mount: "/api/v1/hardware/print, /print-jobs",
    repository: "HardwareRepository",
    domain: "packages/hardware (no domain engine)",
  },
  {
    id: "34",
    module: "Backup & Disaster Recovery",
    apiGroup: "infrastructure",
    mount: "/api/v1/backup",
    repository: "InfrastructureRepository",
    domain: "infrastructure.ts",
  },
  {
    id: "35",
    module: "Devices / Printing",
    apiGroup: "hardware",
    mount: "/api/v1/hardware/events, /cash-drawer, /capabilities",
    repository: "HardwareRepository",
    domain: "packages/hardware (no domain engine)",
  },
  {
    id: "36",
    module: "Industry Engine",
    apiGroup: "none",
    mount: "none (Coming Soon)",
    repository: "none",
    domain: "none",
  },
  {
    id: "37",
    module: "Customization Engine",
    apiGroup: "none",
    mount: "none (Coming Soon)",
    repository: "none",
    domain: "none",
  },
  {
    id: "38",
    module: "Rules / Automation Engine",
    apiGroup: "none",
    mount: "none (Coming Soon)",
    repository: "none",
    domain: "none",
  },
  {
    id: "39",
    module: "System Administration",
    apiGroup: "infrastructure, commerce, enterprise",
    mount: "/api/v1/security, /integrations, /store, /hr",
    repository: "InfrastructureRepository, CommerceRepository, EnterpriseRepository",
    domain: "infrastructure.ts, commerce.ts, enterprise.ts",
  },
];

if (MODULE_API_OWNERSHIP.length !== 39) {
  throw new Error("MODULE_API_OWNERSHIP must list exactly 39 product modules");
}
